# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: camera_service.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'camera_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x63\x61mera_service.proto\x12\x0e\x63\x61mera_service\"!\n\x0c\x46rameRequest\x12\x11\n\tcamera_id\x18\x01 \x01(\t\"U\n\rFrameResponse\x12\x12\n\nframe_data\x18\x01 \x01(\x0c\x12\r\n\x05width\x18\x02 \x01(\x05\x12\x0e\n\x06height\x18\x03 \x01(\x05\x12\x11\n\ttimestamp\x18\x04 \x01(\t\"\"\n\rStatusRequest\x12\x11\n\tcamera_id\x18\x01 \x01(\t\"V\n\x0eStatusResponse\x12\x0f\n\x07running\x18\x01 \x01(\x08\x12\x11\n\tconnected\x18\x02 \x01(\x08\x12\x12\n\nqueue_size\x18\x03 \x01(\x05\x12\x0c\n\x04name\x18\x04 \x01(\t2\xff\x01\n\rCameraService\x12I\n\x08GetFrame\x12\x1c.camera_service.FrameRequest\x1a\x1d.camera_service.FrameResponse\"\x00\x12O\n\x0cStreamFrames\x12\x1c.camera_service.FrameRequest\x1a\x1d.camera_service.FrameResponse\"\x00\x30\x01\x12R\n\x0fGetCameraStatus\x12\x1d.camera_service.StatusRequest\x1a\x1e.camera_service.StatusResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'camera_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FRAMEREQUEST']._serialized_start=40
  _globals['_FRAMEREQUEST']._serialized_end=73
  _globals['_FRAMERESPONSE']._serialized_start=75
  _globals['_FRAMERESPONSE']._serialized_end=160
  _globals['_STATUSREQUEST']._serialized_start=162
  _globals['_STATUSREQUEST']._serialized_end=196
  _globals['_STATUSRESPONSE']._serialized_start=198
  _globals['_STATUSRESPONSE']._serialized_end=284
  _globals['_CAMERASERVICE']._serialized_start=287
  _globals['_CAMERASERVICE']._serialized_end=542
# @@protoc_insertion_point(module_scope)
